CREATE TABLE IF NOT EXISTS CAD_CIDADAO (
    ID INTEGER PRIMARY KEY,
    nome TEXT NOT NULL,
    endereco TEXT NOT NULL,
    bairro TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID INTEGER PRIMARY KEY,
    cidadao_id INTEGER UNIQUE,
    username TEXT UNIQUE NOT NULL,
    senha TEXT NOT NULL,
    tentativas_falhas INTEGER DEFAULT 0,
    ultima_alteracao_senha DATETIME DEFAULT CURRENT_TIMESTAMP,
    bloqueado BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (cidadao_id) REFERENCES CAD_CIDADAO(ID)
);